### ISSUE TITLE
.geno files not accepted. 

### ISSUE THREAD

**Issue by cdomsar** [fgvieira/ngsLD#11]
Hi Filipe, 

I am very interested in using ngsLD to work with some low coverage genomes that I have. I have tried to run these genomes using the same script parameters as the ones you provided in test.sh. First I call glf.gz files with certain defined thresholds:

`angsd -P 8 -bam filelists/afr_nwst.chr38.filelist -ref ref/chr38.canfam.fasta -out ngsLD/afr_nwst.1 -r chr38 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 1 -minMapQ 20 -minQ 20 -minInd 4 -setMinDepth 5 -setMaxDepth 120 -doCounts 1 -GL 1 -doGlf 1 -minIndDepth 5 -doMajorMinor 1`

Then I use this glf.gz file to generate a binary, normal-scale glf.gz (as at test.sh):

`angsd -P 8 -glf ngsLD/afr_nwst.1.glf.gz -fai ref/chr38.canfam.fasta.fai -nInd 4 -doMajorMinor 1 -doPost 1 -doMaf 1 -doGlf 3 -out ngsLD/afr_nwst.2 -r chr38`

I gunzip both files and use the pos.gz:

```
gunzip ngsLD/afr_nwst.2.glf.gz
gunzip ngsLD/afr_nwst.2.glf.pos.gz 

cat afr_nwst.2.glf.pos | wc -l
11544924
```

(for some reason I have lost half of the sites I had in my .bam file, I guess they were not variable:

```
more ref/chr38.canfam.fasta.fai 
chr38	23914537	7	100	101
```

When I try to run ngsLD it has this failure:
```

../../ngsTools/ngsLD/ngsLD --n_threads 10 --verbose 1 --n_ind 1 --n_sites 11544924 --geno ngsLD/afr_nwst.2.glf --log_scale --pos ngsLD/afr_nwst.2.glf.pos --max_kb_dist 10 --min_maf 0.05 --extend_out | sort -k 1,1V -k 2,2V > ngsLD/afr_nwst.2.ld
==> Input Arguments:
	geno: ngsLD/afr_nwst.2.glf
	probs: true
	log_scale: true
	n_ind: 1
	n_sites: 11544924
	pos: ngsLD/afr_nwst.2.glf.pos
	max_kb_dist (kb): 10
	max_snp_dist: 0
	min_maf: 0.050000
	ignore_miss_data: false
	call_geno: false
	N_thresh: 0.000000
	call_thresh: 0.000000
	rnd_sample: 1.000000
	seed: 1576868967
	extend_out: true
	out: (null)
	n_threads: 10
	verbose: 1
	version: 1.1.0 (Dec 20 2019 @ 19:49:52)

==> BINARY input file (always lkl)

=====
ERROR: [main] invalid/corrupt genotype input file!
=====
```

	: Success

What could be the problem? I am maybe wrongly generating my first glf.gz file? When working with the test.sh file, the tests failed. 

```
> ...
> ### Reading data from testLD_2.ld
> ### Parsed a total of 86087 edges (766 kept) between 9268 nodes
> ### Found 7954 unlinked nodes; these will be printed and removed from graph now
> ### Pruning graph (766 edges between 1314 nodes)
> ### Run finished (final graph with 687 nodes)
> ngsLD: test(s) failed!
```

What can be going wrong?

Thank you so much!

**Comment by fgvieira** [comment]
Hi @cdomsar,

I'd try running the first command but with `--doGlf 2` and use the beagle file directly on `ngsLD`.

Also, check the number of sites:
`zcat output.beagle.gz | wc -l`

and the position file can be obtained from the first column of the beagle file.
let me know if you managed to get it to work.
best,

PS - and thanks for a very clear description of the issue! :+1:

**Comment by cdomsar** [comment]
Hi Filipe, 

Thanks for your answer! I tried your solution and apparently it worked when I applied it to a chromosome:

> angsd -P 8 -bam filelists/afr_nwst.chr38.filelist -ref ref/chr38.canfam.fasta -out ngsLD/afr_nwst.1 -r chr38 \
> -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 1 \
> -minMapQ 20 -minQ 20 -minInd 4 -setMinDepth 5 -setMaxDepth 120 -doCounts 1 -GL 1 -doGlf 2 -minIndDepth 5 -doMajorMinor 1

I had 11544924 sites at this chromosome 38 (the smallest of the species I am working with). I ran several command options as in your script test.sh but only using option callgeno gave me a reasonably small file that didnt need 30 hours to run. I created temporary files to check :

> ls ../testchr38/ -latr
> -rwxr-xr-x. 1 cdomsar cdomsar            86190737 ene  9 18:50 afr_nwst.1.beagle.gz
> -rwxr-xr-x. 1 cdomsar cdomsar          168448050 ene 11 13:44 afr_nwst.1.beagle.pos
> -rwxr-xr-x. 1 cdomsar cdomsar  1221005369344 ene 12 10:01 afr_nwst.2.beagle.temp.ld
> -rw-r--r--. 1 cdomsar cdomsar    2614767149056 ene 20 01:13 afr_nwst.2-CGf.beagle.temp.ld
> -rw-r--r--. 1cdomsar cdomsar           1328957159 ene 20 04:54 afr_nwst.2-CG.beagle.temp.ld

My option with callgeno. It took only 3.5 minutes to run, while the other commands (without callgeno option and with callgeno --N_thresh 0.3 --call_thresh 0.9)  required more than 30hours each for 1 chromosome:

> $ngsld --n_threads 10 --verbose 1 --n_ind 4 --n_sites 11544924 --geno $in/afr_nwst.1.beagle.gz --log_scale --pos $in/afr_nwst.1.beagle.pos --max_kb_dist 10 --min_maf 0.05 --extend_out --call_geno > $in/afr_nwst.2-CG.beagle.temp.ld

So far, so good. But when I applied it to a whole genome, my server has repeatedly crashed and the program does not allow me to know how much RAM memory needs. The number of sites raised from 11544924 in chr38 to 1084257619 in the whole genome:

> $ngsld --n_threads 10 --verbose 1 --n_ind 4 --n_sites 1084257619 --geno $in/afr_nwst.autosomes.beagle.gz --log_scale --pos $in/afr_nwst.autosomes.beagle.pos --max_kb_dist 10 --min_maf 0.05 --extend_out --call_geno > $in/afr_nwst.autosomes.beagle.temp.ld

I realized that in your script test.sh (provided with the ngsLD program), ngsld is called with --probs instead of --log_scale. Changing that doesn't work. I have changed the max_kb_dist to 50 and it didnt change either. Directly piping the output of ngsld command to sort gave similar negative result. 

> $ngsld --n_threads 10 --verbose 1 --n_ind 4 --n_sites 1084257619 --geno $in/afr_nwst.autosomes.beagle.gz --probs --pos $in/afr_nwst.autosomes.beagle.pos --max_kb_dist 10 --min_maf 0.05 --extend_out --call_geno | sort -k 1,1V -k 2,2V > > $in/afr_nwst.autosomes.beagle.temp.ld

And finally, allocating 120Gb RAM in my server did not make a change either. 

Do you have any guess of what could be the problem? Is the number of sites too much for the program? would you recommend pruning some SNPs before running ngsLD (although the aim of ngsLD would be to check LD between SNPs and all sites can be informative, wouldn't they?). And finally. afr_nwst is a population. Would you use it per individual?

Best regards and thanks,

Carlos

**Comment by fgvieira** [comment]
Hi Carlos,

Before anything else, if you use `--doGlf 2` in `angsd`, then you should use `--probs` on `ngsLD`. `angsd` stores genotype likelihoods in normal scale on a beagle file.

As for the memory issues, it seems an issue with too many sites... at this point, I'd try to run `angsd` per chromosome (`-r chr1`), and then run `ngsLD` and (if you want to) prune it for each beagle file.

When all is done, you can just concatenate and sort the `ngsLD` output files into a single file.

best,

**Comment by cdomsar** [comment]
Hi Filipe, 

True, that was logic. Sorry if the question seemed lame, I am still learning to work with ngsLD. I successfully outputted the .ld files and I am now interested in plotting the LD decay. I have found these problems when trying to run the tests:

> Rscript --vanilla --slave $ngsldscr/fit_LDdecay.R --ld_files afr_nwst.chr38.ld.list --out afr_nwst.chr38.pdf
> ==> Fitting r2 LD decay assuming a three (rate of decay, max LD and min LD) parameter decay model
> Error in Summary.factor(1:40, na.rm = FALSE) : 
>   ‘max’ not meaningful for factors
> Execution halted

Do you know what could be the cause? I am working with a group of 4 individuals, mean genomewide averages 7X-15X, and just a single chromosome (chr38). Using a number of concatenated chromosomes in .ld did not work either. 

When running the bash script provided:

> cat testLD_2.ld | bash ../scripts/LD_blocks.sh chrSIM_21 2000 5000
> 4 SNPs found!
> Error in library(LDheatmap) : there is no package called ‘LDheatmap’
> Execution halted

I have tried to manually install LDheatmap but packages 'genetics' and 'LDheatmap' seem not to be available for R.3.4:

> > install.packages("LDheatmap")
> Installing package into ‘/home/carlos/R/x86_64-pc-linux-gnu-library/3.4’
> (as ‘lib’ is unspecified)
> Warning: dependency ‘mvtnorm’ is not available
> also installing the dependency ‘genetics’
> 
> trying URL 'https://cloud.r-project.org/src/contrib/genetics_1.3.8.1.2.tar.gz'
> Content type 'application/x-gzip' length 199755 bytes (195 KB)
> ==================================================
> downloaded 195 KB
> 
> trying URL 'https://cloud.r-project.org/src/contrib/LDheatmap_0.99-7.tar.gz'
> Content type 'application/x-gzip' length 971423 bytes (948 KB)
> ==================================================
> downloaded 948 KB
> 
> ERROR: dependency ‘mvtnorm’ is not available for package ‘genetics’
> * removing ‘/home/carlos/R/x86_64-pc-linux-gnu-library/3.4/genetics’
> ERROR: dependency ‘genetics’ is not available for package ‘LDheatmap’
> * removing ‘/home/carlos/R/x86_64-pc-linux-gnu-library/3.4/LDheatmap’
> 
> The downloaded source packages are in
> 	‘/tmp/RtmpPrW3uS/downloaded_packages’
> Warning messages:
> 1: In install.packages("LDheatmap") :
>   installation of package ‘genetics’ had non-zero exit status
> 2: In install.packages("LDheatmap") :
>   installation of package ‘LDheatmap’ had non-zero exit status
> 

I have tried to install the package using other mirrors and solutions from https://stackoverflow.com/questions/25721884/how-should-i-deal-with-package-xxx-is-not-available-for-r-version-x-y-z-wa. Did you ever have any such experience with LDheatmap? Did you need to change the version of R?

Best regards and thanks

**Comment by fgvieira** [comment]
Hi @cdomsar 

I am running `R 3.5.0` and all packages installed fine. Can you try updating `R` (`mvtnorm` requires R ≥ 3.5.0)? After that, can you try running the example and you dataset again?

**Comment by cdomsar** [comment]
Hi Filipe, 

I solved all problems thanks to your recommendations, we could close this thread. 

Thank you very much for all support, 

Carlos
