### ISSUE TITLE
Installation error: fatal error: gsl/gsl_rng.h: No such file or directory

### ISSUE THREAD

**Issue by debjyoti88** [fgvieira/ngsLD#12]
Hi @fgvieira,
I am trying to install ngsLD in Ubuntu 18.04 and having the following error while running the 

```
Makefile:
make
g++ -I./shared -I/opt/anaconda1anaconda2anaconda3/include -O3 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -c ./shared/gen_func.cpp
In file included from ./shared/gen_func.cpp:1:0:
./shared/gen_func.hpp:12:10: fatal error: gsl/gsl_rng.h: No such file or directory
 #include <gsl/gsl_rng.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:20: gen_func.cpp] Error 1
```
I tried the solutions you suggested over [here](https://github.com/fgvieira/ngsDist/issues/3). But none of them work. Could you please help me in the installation? 

Thank you.

**Comment by debjyoti88** [comment]
Hi,

I was able to solve this issue by setting the library paths.

Best,

Debjyoti

**Comment by jgpeniche** [comment]
> 
> 
> Hi,
> 
> I was able to solve this issue by setting the library paths.
> 
> Best,
> 
> Debjyoti

Hi! I'm getting the same error, I'm very new to this topic. I'm working in windows 10, would you be so kind of elaborating on how do I set library paths please?

Thanks in advance for your time!

**Comment by fgvieira** [comment]
Hi @jgpeniche,

you need to install [GNU Scientific Library](https://www.gnu.org/software/gsl/) but I have never tried to do it on Windows. Also, `ngsLD` has only been tested on Linux and not sure how it will behave on Windows.

best,

**Comment by debjyoti88** [comment]
Hi guys,

I'm probably not the intended recipient of this email chain. You might want
to remove me and add the intended recipient.

Good luck with the installation, nonetheless :)

Best,
Debjyoti.
