### ISSUE TITLE
compilation error with ubuntu 14.04

### ISSUE THREAD

**Issue by hrwang** [fgvieira/ngsLD#14]
Dear @fgvieira,

I have failed to compile ngsLD, the error message looks like this:

g++ -I./shared  -O3 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -c ngsLD.cpp -lgsl -lgslcblas -lm -lz -lpthread
ngsLD.cpp: In function ‘int main(int, char**)’:
ngsLD.cpp:125:42: error: no matching function for call to ‘read_file(char*&, char***)’
     if(read_file(pars->pos, &pars->labels) != pars->n_sites)
                                          ^
ngsLD.cpp:125:42: note: candidates are:
In file included from ./shared/read_data.hpp:3:0,
                 from ngsLD.hpp:4,
                 from ngsLD.cpp:22:
./shared/gen_func.hpp:55:8: note: char** read_file(const char*, uint64_t, uint64_t, uint64_t)
 char **read_file(const char*, uint64_t, uint64_t, uint64_t);
        ^
./shared/gen_func.hpp:55:8: note:   candidate expects 4 arguments, 2 provided
./shared/gen_func.hpp:56:10: note: double** read_file(const char*, uint64_t, uint64_t, int, uint64_t)
 double **read_file(const char*, uint64_t, uint64_t, int, uint64_t);
          ^
./shared/gen_func.hpp:56:10: note:   candidate expects 5 arguments, 2 provided
make: *** [ngsLD] Error 1

Thanks!

**Comment by fgvieira** [comment]
Hi @hrwang ,
can you try now? I've been changing some things and forgot to push some files.

**Comment by hrwang** [comment]
Works perfectly for me now, thanks!
