### ISSUE TITLE
ERROR: [read_geno] wrong GENO file format. Less fields than expected!

### ISSUE THREAD

**Issue by alissaseverson** [fgvieira/ngsLD#16]
Hello,

I'm getting the above error with my input files when I try to run ngsLD. For my data set I'm merging multiple beagle files with python (pandas), which I'm worried is leading to formatting issues. I've double checked the number of samples and sites and they are correct. I've also double checked the default pandas encoding and it's utf-8, so it should be ok? For testing I head-ed my beagle file, which I've attached below, and I got the same error. The command I run is:
`ngsLD --geno all_samples.head.beagle.gz --probs --n_ind 336 --n_sites 9 --pos all_samples.head.pos.txt --max_kb_dist 500 --min_maf 0.05`
and the following output is printed to the screen:
==> Input Arguments:
	geno: all_samples.head.beagle.gz
	probs: true
	log_scale: false
	n_ind: 336
	n_sites: 9
	pos: all_samples.head.pos.txt
	max_kb_dist (kb): 500
	max_snp_dist: 0
	min_maf: 0.050000
	ignore_miss_data: false
	call_geno: false
	N_thresh: 0.000000
	call_thresh: 0.000000
	rnd_sample: 1.000000
	seed: 1595268149
	extend_out: false
	out: (null)
	n_threads: 1
	verbose: 1
	version: 1.1.0 (Jul 13 2020 @ 15:06:32)

==> GZIP input file (not BINARY)
\> Reading data from file...

\=====
ERROR: [read_geno] wrong GENO file format. Less fields than expected!
\=====

	: Success

I'm wondering if the 'less fields than expected' suggests that there's still something going wrong with the tab delimitation? I also find it curious that it's not detecting the header line? I would greatly appreciate any help or insight! Happy to provide any other information needed.

Thank you,
Alissa
[all_samples.head.beagle.gz](https://github.com/fgvieira/ngsLD/files/4949492/all_samples.head.beagle.gz)
[all_samples.head.pos.txt](https://github.com/fgvieira/ngsLD/files/4949493/all_samples.head.pos.txt)

**Comment by fgvieira** [comment]
Hi Alissa,

thanks for reporting the bug.
It seems it was an issue with the header of your beagle file that it was not being detected correctly.

Can you try the latest version and let me know?

**Comment by alissaseverson** [comment]
That seems to have fixed it, thanks!!
