### ISSUE TITLE
ngsld pruning running forever 

### ISSUE THREAD

**Issue by HomereAMK** [fgvieira/ngsLD#21]
Hello Filipe,

I got this script that has been running forever now (142hours now).
the input is a beagle file coming from low-coverage whole-genome sequencing 

#PBS -l nodes=2:ppn=40
#PBS -l walltime=100:00:00
#PBS -l mem=220gb
#Run ngsLD

perl /services/tools/ngstools/20190624/ngsLD/scripts/prune_graph.pl \
       --in_file $LDFILES \
       --max_kb_dist 2000 \
       --min_weight 0.5 \
       --out $OUTPUTFOLDER/xxx_unlinked2.id

I get an output with only the SNPs positions but not the LD estimation...
`head ../$OUTPUTFOLDER/xxx_unlinked2.id`
scaffold10:10032428
scaffold10:10041873
scaffold10:10042064
scaffold10:10042614
scaffold10:10059026
scaffold10:1006231
scaffold10:10080234
scaffold10:10085198
scaffold10:1009028
scaffold10:10090757

Is it because it's low cov?
All the best,
Homère

**Comment by fgvieira** [comment]
Hi Homere,

from what I understand, you are running the `prune_graph.pl` script with a beagle file?

If so, you need to run `ngsLD` with the beagle file to calculate LD between pairs of SNPs, and only then use the script `prune_graph.pl` to prune linked sites.
