### ISSUE TITLE
Example GL File

### ISSUE THREAD

**Issue by gaxyz** [fgvieira/ngsLD#27]
Hello,

I am trying to run ngsLD, but I am having trouble figuring out the correct input format for genotype likelihoods. I tried beagle gzipped output and a modified version of it (for only one individual and four loci):

```
-1      0       0.333333        0.333333 

0       -1      0.458889        0.541111

0       2       0.000000        1.000000

-1      0       1.000000        0.000000
```

But it does not work (error:`cannot read GZip GENO file. Check GENO file and number of sites!`).

Could you please provide an example GL file?

Thanks!

gaston

**Comment by fgvieira** [comment]
You can check the description of the beagle format [here](http://popgen.dk/angsd/index.php/Genotype_Likelihoods#Output).

**Comment by fgvieira** [comment]
yes, but is´t has to be gziped
