### ISSUE TITLE
LD pruning issue

### ISSUE THREAD

**Issue by TrishikaS** [fgvieira/ngsLD#29]
Hi, 

I'm trying to do the LD pruning on a file generated using these parameters (just for chr1):
$NGSLD/ngsLD --geno $INPUT/10x_chr1_GL.beagle.gz \
--probs --ignore_miss_data --rnd_sample 0.05 --seed 1 \
--n_ind 20 --n_sites 262117 --pos $POS  --out $OUT/test1 --n_threads 8
 
When I run perl script [perl $NGSLD/scripts/prune_graph.pl --in_file $OUT/test1 --max_kb_dist 100 --min_weight 0.5 --out $OUT/test1LD] it always freezes half way through the chr1 and I get a file just with a proportion of unlinked sites.
This is where it gets stuck...
Reading data from /mnt/nina/results_8/realigned_final/chr_bam/chr1_bam/ngsLD/test1
Found 1000000 edges (347873 passed filters) between 78450 nodes so far...
Found 2000000 edges (699468 passed filters) between 182622 nodes so far...
Parsed a total of 2913928 edges (941904 kept) between 262062 nodes
Found 52632 unlinked nodes; these will be printed and removed from graph now
Pruning graph (941904 edges between 209430 nodes)

In order to overcome this issue a colleague who had the same issue with pruning suggested to add chr2 in sites file (-pos) and then run perl script so it would freeze somewhere in the middle of chr2, and that worked ok and I got all unlinked sites for the chr1.

However, I would like to know if there is a more elegant way of fixing this issue? 

Also when I add max_kb_dist 300 in the first step, it would still use default value of 100kb in LD calculations, what could be the issue there?

Thank you in advance!

**Comment by fgvieira** [comment]
It seems a similar issue to #22 and #25, where the prunning script becomes very slow or irresponsive (usually for lack of memory). 

When it gets stuck, how many sites do you have? How much memory do you have?

**Comment by TrishikaS** [comment]
When it got stuck I had around 50000 sites, and it should be around 98000. I have 16cpu-64ram.

**Comment by fgvieira** [comment]
From the log you posted of just chr1, it seems you have 262062 sites, 52632 of them are unlinked to start with; so it will try to prune 209430 sites.

When it hangs, can you check the cpu and memory usage of the prunning script?

**Comment by TrishikaS** [comment]
Thank you for your swift replies!

Actually in sites file I have 262117 sites (not sure why it shows 262062 when it runs the script)...
When it hangs it uses 100%CPU and 2.8% MEM

**Comment by fgvieira** [comment]
And why do you say it hangs?
Could it just be that it was just poorly implemented by me and very slow? :smile:

**Comment by TrishikaS** [comment]
haha! I am not an expert, but if I let it run for almost a whole day, and nothing happens, I guess it got stuck somewhere.
The strange thing is, if I don't use --ignore_miss_data --rnd_sample 0.05 --seed 1 in the first step (for LD calculation), the LD pruning is working fine and the run is finished within few hours. 
/### Parsed a total of 119462097 edges (228238 kept) between 228242 nodes
/### Pruning graph (228238 edges between 228242 nodes)
/### Run finished (final graph with 228238 nodes)

**Comment by fgvieira** [comment]
`--ignore_miss_data` should just affect how the frequencies are calculated, with this option ignoring missing genotypes.
`--rnd_sample 0.05` should result in a smaller file
`--seed 1` should have no effect in this case.

Do you think you can send me the `ngsLD` output files for these two cases together with the `stdout` log?
thanks,

**Comment by TrishikaS** [comment]
Yes, I will just need to run it again (I didn't save the stdout log file) and then I will send you all files.
Thanks!

**Comment by TrishikaS** [comment]
Here it is, this is the first option without --rnd_sample: https://we.tl/t-ORQ8nGoEPp
and the second one with --rnd_sample option:  https://we.tl/t-CSp9QyF6Pf 

Thanks!

**Comment by fgvieira** [comment]
For the first file, it seems the script finished ok (from the stdout); however, very few SNPs are removed and that might eb because the input file has some extra columns. Try removing columns `2,3,5,6` from `LD_0504_maf01_kb300`.

As for the second file, it does not have the extra columns and is much smaller, so maybe that is why if finishes so fast.

**Comment by TrishikaS** [comment]
Thanks a lot, I will try removing those columns. 

However, regarding the second file, the issue there is that it never finishes the run completely, it stays stuck at "Pruning graph (941904 edges between 209430 nodes)", and it never gets to the ...."### Run finished (final graph with ...).

**Comment by fgvieira** [comment]
Hi TrishikaS,

I've just pulled another version of the `prune_graph.pl` script with some extra input checks and prunning progress.
I tried running your example and it seems to work, even though it is quite slow. I started it yesterday and it is still running:
```
# Found 1000000 edges (347873 passed filters) between 78450 nodes so far...
# Found 2000000 edges (699468 passed filters) between 182622 nodes so far...
### Parsed a total of 2913928 edges (941904 kept) between 262062 nodes
### Found 52632 unlinked nodes; these will be printed and removed from graph now!
### Pruning graph (941904 edges between 209430 nodes)
# 1000 nodes pruned; 208417 linked nodes remaining ...
# 2000 nodes pruned; 207415 linked nodes remaining ...
# 3000 nodes pruned; 206399 linked nodes remaining ...
# 4000 nodes pruned; 205385 linked nodes remaining ...
# 5000 nodes pruned; 204372 linked nodes remaining ...
# 6000 nodes pruned; 203362 linked nodes remaining ...
# 7000 nodes pruned; 202351 linked nodes remaining ...
# 8000 nodes pruned; 201338 linked nodes remaining ...
# 9000 nodes pruned; 200323 linked nodes remaining ...
# 10000 nodes pruned; 199307 linked nodes remaining ...
# 11000 nodes pruned; 198295 linked nodes remaining ...
# 12000 nodes pruned; 197282 linked nodes remaining ...
# 13000 nodes pruned; 196250 linked nodes remaining ...
# 14000 nodes pruned; 195233 linked nodes remaining ...
# 15000 nodes pruned; 194220 linked nodes remaining ...
# 16000 nodes pruned; 193191 linked nodes remaining ...
# 17000 nodes pruned; 192162 linked nodes remaining ...
# 18000 nodes pruned; 191144 linked nodes remaining ...
# 19000 nodes pruned; 190113 linked nodes remaining ...
# 20000 nodes pruned; 189092 linked nodes remaining ...
# 21000 nodes pruned; 188051 linked nodes remaining ...
# 22000 nodes pruned; 187019 linked nodes remaining ...
# 23000 nodes pruned; 185983 linked nodes remaining ...
# 24000 nodes pruned; 184947 linked nodes remaining ...
# 25000 nodes pruned; 183920 linked nodes remaining ...
# 26000 nodes pruned; 182880 linked nodes remaining ...
# 27000 nodes pruned; 181841 linked nodes remaining ...
# 28000 nodes pruned; 180791 linked nodes remaining ...
# 29000 nodes pruned; 179751 linked nodes remaining ...
# 30000 nodes pruned; 178704 linked nodes remaining ...
# 31000 nodes pruned; 177664 linked nodes remaining ...
# 32000 nodes pruned; 176612 linked nodes remaining ...
# 33000 nodes pruned; 175555 linked nodes remaining ...
# 34000 nodes pruned; 174491 linked nodes remaining ...
# 35000 nodes pruned; 173419 linked nodes remaining ...
# 36000 nodes pruned; 172327 linked nodes remaining ...
# 37000 nodes pruned; 171241 linked nodes remaining ...
```

I'd say it will take around 3 days to finish. If you want something faster, you can look into #25 where they basically implemented some functionalities of the `prune_graph.pl` script in python and claim it was much faster.

**Comment by fgvieira** [comment]
The python script has been added to the repo. 😄
