### ISSUE TITLE
error when trying to plot LD decay

### ISSUE THREAD

**Issue by rtfcoimbra** [fgvieira/ngsLD#3]
Hi,

I ran ngsLD for my data with the following command:

`ngsLD --geno $GL --probs --n_ind $N_IND --n_sites $N_SITES --pos $POS --max_kb_dist 1000 --min_maf 0.05 --out ${NAME}.ld --n_threads 10`

Now I'm trying to plot the LD decay for my data with the command:

`cat ${NAME}.ld | awk 'rand()<0.1' | Rscript --vanilla --slave fit_LDdecay.R --out plot.pdf`

However, I'm getting the following message:

```
Random seed: 30916
==> Fitting r2 LD decay assuming a three (rate of decay, max LD and min LD) parameter decay model
Error in open.connection(file, "rt") : cannot open the connection
Calls: read.table -> open -> open.connection
In addition: Warning message:
In open.connection(file, "rt") :
 cannot open compressed file 'Scaffold_0:11284', probable reason 'No such file or directory'
Execution halted
```

I don't quite understand why I'm getting this error/warning messages. 'Scaffold_0:11284' is not a file, it's just a site in the ngsLD output file. Any tips on how I can fix that?

**Comment by fgvieira** [comment]
Hi @rtfcoimbra,

the input to `ngsLD` are one/several LD output files.
Can you try:
```
ls ${NAME}.ld | Rscript --vanilla --slave fit_LDdecay.R --out plot.pdf
```

**Comment by rtfcoimbra** [comment]
Thanks for your response Filipe!
Now I tried this:

```
cat ${NAME}.ld | awk 'rand()<0.1' > ${NAME}.sampled.ld
ls ${NAME}.sampled.ld | Rscript --vanilla --slave fit_LDdecay.R --ld r2 --n_ind $N_IND --max_kb_dist 200 --fit_boot 100 --fit_bin_size 1000 --fit_level 100 --plot_data --plot_scale 3 --out plot.pdf
```

but I get a different error

```
Random seed: 14632
==> Fitting r2 LD decay assuming a one (rate of decay) parameter decay model
Error in Summary.factor(1:200, na.rm = FALSE) :
  ‘max’ not meaningful for factors
Execution halted
```

Do I have to use `--plot_x_lim` or `--plot_axis_scales`?

**Comment by rtfcoimbra** [comment]
Thanks for your response Filipe!
Now I tried this:

```
cat ${NAME}.ld | awk 'rand()<0.1' > ${NAME}.sampled.ld
ls ${NAME}.sampled.ld | Rscript --vanilla --slave fit_LDdecay.R --ld r2 --n_ind $N_IND --max_kb_dist 200 --fit_boot 100 --fit_bin_size 1000 --fit_level 100 --plot_data --plot_scale 3 --out plot.pdf
```

but I'm getting a different error:

```
Random seed: 14632
==> Fitting r2 LD decay assuming a one (rate of decay) parameter decay model
Error in Summary.factor(1:200, na.rm = FALSE) :
  ‘max’ not meaningful for factors
Execution halted
```

and if I add `--plot_x_lim 1000` to the command, then I get the following error:

```
Random seed: 96029
==> Fitting r2 LD decay assuming a one (rate of decay) parameter decay model
Error in optim(par$init, fit_eval, obs_data = x, method = "BFGS") :
  initial value in 'vmmin' is not finite
Calls: ddply ... loop_apply -> <Anonymous> -> .fun -> append -> optim
In addition: Warning message:
In Ops.factor(par[1], dist) : ‘*’ not meaningful for factors
Execution halted
```

Do I have to change anything in the options?

**Comment by fgvieira** [comment]
How many individuals do you have?
Also, can you send me a small example file so I can reproduce the error?

**Comment by rtfcoimbra** [comment]
I have 50 individuals. Yes, I can. I just sampled the data that I used.

`awk 'rand()<0.001' data.sampled.ld | pigz >` [data.sampled.ld.gz](https://github.com/fgvieira/ngsLD/files/3131437/data.sampled.ld.gz)

**Comment by fgvieira** [comment]
I tried running your example:
```
ls data.sampled.ld.gz | Rscript --vanilla --slave scripts/fit_LDdecay.R --ld r2 --n_ind 50 --max_kb_dist 200 --fit_boot 100 --fit_bin_size 1000 --fit_level 100 --plot_data --plot_scale 3 --out plot.pdf
```

and it worked fine:
[plot.pdf](https://github.com/fgvieira/ngsLD/files/3134060/plot.pdf)

**Comment by rtfcoimbra** [comment]
Hmm... So the issue must be with the servers that I'm using here, although I installed all the required packages. I'll try to figure that out and if I find anything significant I'll let you know. For now I'm closing this issue. Thank you!

**Comment by lucasrocmoreira** [comment]
Hi,

I am getting the same error when trying to plot LD decay as well. Did you figure out what that error might be? Thanks.

```
Error in Summary.factor(1:200, na.rm = FALSE) :
  ‘max’ not meaningful for factors
Execution halted
```

**Comment by fgvieira** [comment]
How many files do you have, and how are you running the plotting script?

**Comment by lucasrocmoreira** [comment]
I am plotting a single file with 70 samples. I am running the following command:

``ls Picoides_pubescens-subset.LD | Rscript --vanilla --slave ~/programs/ngsTools/ngsLD/scripts/fit_LDdecay.R --ld r2 --n_ind 70 --max_kb_dist 200 --fit_boot 100 --fit_bin_size 1000 --fit_level 100 --plot_data --plot_scale 3 --out plot.pdf``

I have also tried different combinations of options (adding and leaving some out) and using `--ld_files` by creating a text file with the name of my LD file. All of these produce the same error. 

I am using R version 3.4.1. I wonder if this has to do with the version of R or any required package.

**Comment by fgvieira** [comment]
can you try with a smaller file? Just randomly sample (e.g.) 1000 lines and check if it still fails.
If it does, can you send me the file?

**Comment by lucasrocmoreira** [comment]
Yeah, I tried and I get the same error.

Here is the file:
`shuf -n 1000 Picoides_pubescens.LD >` [Picoides_pubescens-subset.LD.gz](https://github.com/fgvieira/ngsLD/files/3870290/Picoides_pubescens-subset.LD.gz)

**Comment by fgvieira** [comment]
Hi @lucasrocmoreira 

just tried with your file and it went fine:
```
ls Picoides_pubescens-subset.LD | Rscript --vanilla --slave ./scripts/fit_LDdecay.R --ld r2 --n_ind 70 --max_kb_dist 200 --fit_boot 100 --fit_bin_size 1000 --fit_level 100 --plot_data --plot_scale 3 --out plot.pdf
Random seed: 31226
==> Fitting r2 LD decay assuming a one (rate of decay) parameter decay model
                          File LD   DecayRate LDmax LDmin DecayRate_CI.u DecayRate_CI.l LDmax_CI.l LDmax_CI.u LDmin_CI.l LDmin_CI.u
1 Picoides_pubescens-subset.LD r2 0.005503559     0     0    0.002043028    0.011275621          0          0          0          0
==> Plotting data...
```

Are you using the latest script version?

**Comment by lucasrocmoreira** [comment]
Hi Filipe,

It turns out I had the old version of ngsLD installed (v 1.0.0), as part of the ngsTools package. After I re-installed it, it worked perfectly. I also made sure I had all the necessary packages installed in R before running the script.

Thanks a lot for taking the time to help!

**Comment by rtfcoimbra** [comment]
Just as a feedback, I revisited my data after seeing @lucasrocmoreira comment and turns out that the issue I had before was also due to an old version installed with the ngsTools package. Installing ngsLD and all the required packages for the scripts now works great!

Thanks!

**Comment by fgvieira** [comment]
@rtfcoimbra good to hear that!!

@lucasrocmoreira did you manage to get it to work?

**Comment by lucasrocmoreira** [comment]
@fgvieira yes, it's working with the newest version. Thanks for following up.
