### ISSUE TITLE
clarification of options

### ISSUE THREAD

**Issue by cbird808** [fgvieira/ngsLD#33]
it is difficult to interpret exactly what some of the options do in the main `README.md`

`--n_ind ` and `--n_sites` - I know this is the number of individuals and sites, but that's easily inferred from the input file so I'm wondering if there's something I'm missing
`--ignore_miss_data`  - does this only pertain to called genotypes?  how is missing data defined?
`--N_thresh`    - what is this value?  it's a double so minor allele freq?
`--call_thresh` - what is this value?  it's a double so minor allele freq?

**Comment by fgvieira** [comment]
`--n_ind` and `--n_sites`: are required as a sanity check of the input files.
`--ignore_miss_data`: it will ignore all steps where at least one genotype has missing data, when estimating per site maf and the haplotype freqs. it is defined if all 3GL are equal (see #32)

`ngsLD` calls genotypes by setting the highest GL to 1 and the rest to 0, so:
`--N_thresh`: minimum threshold to call a genotype. If highest GL is lower than this, set as missing data (all 3 GL equal)
`--call_thresh`: minimum threshold to call a genotype. If highest GL is lower than this, leave as is (do not call geno). This allows to only call genotypes at positions with high confidence, leaving the GLs as-is for the more uncertain ones.

**Comment by cbird808** [comment]
Perfect, thank you!  Adding the threshold description to the readme would probably benefit others

Fyu, needing to enter the sites and num ind gets to be a pain when running ngsld on every chromosome from every pop sample separately.  Not insurmountable, but an extra challenge for students

Great program!  Thanks for maintaining this!

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
