### ISSUE TITLE
missing data affects `--min_maf`

### ISSUE THREAD

**Issue by cbird808** [fgvieira/ngsLD#34]
Is the `--min-maf`    filter supposed to work with GL or GP data?  I'm pretty certain that missing GL or GP data coded as 0.33, 0.33, 0.33 will cause this filter not function as intended.  Hopefully this will be addressed by my question about the coding of genotypes with 0 reads.  Thanks for you help!

**Comment by fgvieira** [comment]
MAF is estimated from GL, wether you call genos or not (see #33) and including all siets by default (even the missing ones). If you use `--ignore_miss_data`, then positions with missing data will be ignored when calculating MAF.
