### ISSUE TITLE
Error on the number of sites  - angsd/beagle input format ?

### ISSUE THREAD

**Issue by clairemerot** [fgvieira/ngsLD#4]
Hi!
I have been looking for a long time for a good tool to calculate LD on genotype likelihood from low coverage data. And ngsLD seems to be perfect for that, thanks! 

I am trying to use the direct output from angsd (beagle obtain with -doGlf 2) as explained in https://github.com/fgvieira/ngsLD/issues/1. For now I am trying only on one chromosome at a time with limited number of snps (I started with the small LG6) but I always get the same issue that the number of sites provided does not fit the number of labels. 
Have you ever encouter this problem? What am I doing wrong?

Below is the command and the message I get. Thanks a lot for your attention.

Best regards,
Claire

ps: I am also wondering how this work to calculate LD if I provide a beagle with multiple LG (135 including chromosomes and scaffolds) and many snps (2 000 000). Should I reduced the beagle to the most frequent snps? Should I partition the data to run ngsLD Lg by LG ?

ngsLD --geno window_LG6_440-2588164_2084_snps.beagle.gz --probs --n_ind 1446 --n_sites 2084 --max_kb_dist 0 --max_snp_dist 0 --out essai_ngsLD --extend_out
==> Input Arguments:
        geno: window_LG6_440-2588164_2084_snps.beagle.gz
        probs: true
        log_scale: false
        n_ind: 1446
        n_sites: 2084
        pos: (null)
        max_kb_dist (kb): 0
        max_snp_dist: 0
        min_maf: 0.001000
        ignore_miss_data: false
        call_geno: false
        N_thresh: 0.000000
        call_thresh: 0.000000
        rnd_sample: 1.000000
        seed: 1557770562
        extend_out: true
        out: essai_ngsLD
        n_threads: 1
        verbose: 1
        version: 1.1.0 (May 13 2019 @ 11:34:43)

==> GZIP input file (not BINARY)
> Reading data from file...
> Header found! Skipping line...
==> Calculating MAF for all sites...
==> Getting sites coordinates
==> Getting sites labels

=====
ERROR: [main] number of labels does not match number of sites!
=====

        : Numerical result out of range

**Comment by fgvieira** [comment]
Hi Claire,

thanks for your interest on `ngsLD`.

Looking at your error, it seems you forgot to provide a `positions` file. In your case, it is just the two first columns from the beagle file (without the header).
I know I could read it from the beagle file, but it is just so it is consistent with binary files (where position info is not available).

PS - you can provide `ngsLD ` with multiple LG (no need to partition your file), but it will only calculate LD between sites on the same LG. As for the number of SNPs, you can calculate LD on all of them, but it might be a bit slow. Depending on your goal, you can randomly sample your sites (`--rnd_sample`), or restrict your LD calculation to SNPs less than X kbps apart (`--max_kb_dist`).

**Comment by clairemerot** [comment]
Thanks a lot for your answer, it seems to be running fine now. 
I had completely missed the --pos option. Sorry!

I'll do the LD within all the LG because I'm interested in inversions and structural variations. Yet, as you said that might makes a lot of snpsand be slow. I'll try to subset either on random snps, or on snpw with maf >10-20% or so.

Calculating between LGs could be useful in the future, not for LGs themselves but for unassembled scaffolds (In another species, we have a very fragmented genome and would like to calculate LG between scaffolds that are possibly in the same rearrangement). I might try to trick the program by renaming the positions in the beagle and pos files into a single "pseudo-LG"...

Thanks for your help and this very useful tool!!
Claire

**Comment by fgvieira** [comment]
Glad to hear it is working now. :)

Let me know if you ever want to calculate LD between LG. I can try to add an option to ignore chr/contig names (even though that might mess up the distance between SNPs).
