### ISSUE TITLE
program killed

### ISSUE THREAD

**Issue by clydeandforth** [fgvieira/ngsLD#40]
I'm trying to calculate pairwise LD from genotype likelihoods in beagle format which have been estimated using Angsd. I get the following error when using ngsLD:

`/var/spool/torque/mom_priv/jobs/38033308.SC: line 34: 16954 Killed                  ngsLD --geno "$PROBS" --n_ind 484 --n_sites "$NUM_SITES" --pos pos_file.txt --max_kb_dist 1000 --probs --call_geno --n_threads 24`

I've been checking my input files with others such as those provided in issue #16 , but I can't find any difference in the files. Any idea what is causing the error?

I first load the following modules on torque/moab:
```
module purge
module load  tools gsl/2.7 perl/5.30.2 samtools/1.9 gcc/7.4.0 intel/perflibs/2020_update4 R/4.2.0 htslib/1.9 ngstools/20190624
```
Then program the run like this:

`ngsLD --geno "$PROBS"  --n_ind 484 --n_sites "$NUM_SITES" --pos pos_file.txt --max_kb_dist 1000 --probs --call_geno --n_threads 24`

The first few lines of the beagle likelihoods file (abbreviated):
```
marker  allele1 allele2 Ind0    Ind0    Ind0 
Contig0_98      2       0       0.333333        0.333333        0.333333 
```
and the position file:
Contig0 98 
Contig0 108 
Contig0 114 
Contig0 166 
Contig0 176 

Thanks,

James

**Comment by fgvieira** [comment]
Could it be that you are running out of memory? How big is your file? How much memory do you have?

**Comment by clydeandforth** [comment]
Yes, it was just memory. My gzipped beagle file is 25Gb. I thought i had assigned a lot of memory and didn't appreciate how much the program would need, i.e 800Gb

    resources_used.mem = 797652364kb
    resources_used.vmem = 797953964kb
I'll close this

Thanks!
