### ISSUE TITLE
install: fatal error: gsl/gsl_rng.h: No such file or directory

### ISSUE THREAD

**Issue by RachelxGray** [fgvieira/ngsLD#46]
Hello, 

I am having the same issue as here: https://github.com/fgvieira/ngsLD/issues/12, 

I do not understand how this was resolved with library paths. 

I have tried to set the library path as both: 

```
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/Software/gsl_1.15/gsl-1.5

 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/Software/gsl_1.15/gsl-1.5/gsl/gls_rng.h
```
With both I get the same issue: 

```
g++ -I./shared -I/usr/local/include   -O3 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -c ./shared/gen_func.cpp
In file included from ./shared/gen_func.cpp:1:0:
./shared/gen_func.hpp:12:25: fatal error: gsl/gsl_rng.h: No such file or directory
 #include <gsl/gsl_rng.h>
                         ^
compilation terminated.
make: *** [gen_func.cpp] Error 1

```

Could anyone suggest how to set fix this issue with the correct library path?

Thank you.

**Comment by fgvieira** [comment]
The `Makefile` uses `pkg-config` to find installed libraries. How did you install `gsl`?

**Comment by Truongphikt** [comment]
I also run into this problem. I install the `gsl` by command:
```
sudo apt install generator-scripting-language
```
But I still get an error about `gsl` installing.
![image](https://github.com/fgvieira/ngsLD/assets/141545014/cbbee258-f772-40dd-9704-850f25fa9b93)

**Comment by fgvieira** [comment]
`gsl` is the GNU Scientific Library.
