### ISSUE TITLE
--min_weight flag what does it do?

### ISSUE THREAD

**Issue by albinap** [fgvieira/ngsLD#5]
Could you give a bit more detail about the function of the --min_weight flag? This is what I could find: "minimum weight of an edge to assume nodes are connected" and I am not sure I understand what it does

**Comment by fgvieira** [comment]
the filtering script represents the linked nodes as a graph where SNPs are nodes and the linkage between them edges. In this representation, the weight of an edge is the LD between the two connected nodes (SNPs); so, the minimum weight is the minimum LD between two SNPs that will be considered. All LD values under `--min_weight` will be ignored.
