### ISSUE TITLE
 invalid distance between adjacent sites

### ISSUE THREAD

**Issue by etwatson** [fgvieira/ngsLD#7]
Greetings!

I ran into an error running the ngsLD software and get the below output. I use the beagle input, and I have converted the positions in the file from _de novo_ RAD sites to where these sites map to the reference genome. Maybe I have made an error in converting the site coordinates, so some help in understanding this error would do wonders. 

Thanks,
Eric

--> Input Arguments:
	geno: RILs.refpos.beagle.gz
	probs: true
	log_scale: false
	n_ind: 71
	n_sites: 7586
	pos: RILs.refpos.beagle.sites
	max_kb_dist (kb): 5
	max_snp_dist: 0
	min_maf: 0.001000
	ignore_miss_data: false
	call_geno: false
	N_thresh: 0.000000
	call_thresh: 0.000000
	rnd_sample: 1.000000
	seed: 1565042370
	extend_out: false
	out: RILs.ld
	n_threads: 30
	verbose: 1
	version: 1.1.0 (Aug  1 2019 @ 14:12:13)
--> GZIP input file (not BINARY)
-> Reading data from file..
--> Calculating MAF for all sites...
--> Getting sites coordinates

ERROR: [read_pos] invalid distance between adjacent sites!

Numerical result out of range

**Comment by Morgan-McCarthy** [comment]
Hey did you find out what the problem was here? I've run into the same issue.

**Comment by fgvieira** [comment]
It usually means that the sites are not sorted, so the distance between sites is negative.

**Comment by Morgan-McCarthy** [comment]
Thanks for the follow up!
