### ISSUE TITLE
Is the format of input geno file same with the ngsDist?

### ISSUE THREAD

**Issue by biozzq** [fgvieira/ngsLD#9]
Dear @fgvieira 

I found you have given a detailed description of the input format of ngsDist but not ngsLD. For example, the file can have a header and an arbitrary number of columns preceeding the actual data (that will all be ignored), much like the Beagle file format. Can ngsLD use the beagle file generated by ANGSD as input?

Kind regards,
Zhuqing

**Comment by fgvieira** [comment]
Hi biozzq,

yes, ngsLD can use the beagle file from ANGSD as input.
